# Generated by Django 5.0.6 on 2025-06-30 17:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_actividad_alter_curso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='act',
            field=ckeditor.fields.RichTextField(verbose_name='Actividad'),
        ),
    ]
